# Generated by Django 5.2.3 on 2025-06-18 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerCollectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('box', 'box'), ('rack', 'rack'), ('plate', 'plate'), ('tray', 'tray')], default='plate', max_length=10, unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bottle', 'bottle'), ('flask', 'flask'), ('jar', 'jar'), ('specimen_container', 'specimen_container'), ('tube', 'tube'), ('well', 'well')], default='well', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContainerCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('size', models.IntegerField()),
                ('container_collection_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='containers.containercollectiontype')),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('location_x', models.IntegerField()),
                ('location_y', models.IntegerField()),
                ('location_name', models.CharField(max_length=5)),
                ('container_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='containers.containercollection')),
                ('container_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='containers.containertype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('container_collection__isnull', False)), fields=('location_x', 'location_y', 'container_collection'), name='unique_container_location')],
            },
        ),
    ]
